### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NeiltonSeguins** [guilhermeonrails/teste-deleta-depois#1]
imagem aparece quadruplicada quando diminui o zoom

**Comment by guilhermeonrails** [comment]
E ai Nei, como vai?
Muito obrigado pela ajuda. Vou pesquisar e descobrir como resolver este problema.

**Comment by guilhermeonrails** [comment]
Fala Nei
Consegui corrigir o problema incluindo o código:

```
background-repeat: no-repeat;
```

Mais uma vez, obrigado.
